/**
 * Mentor Feature Constants
 * All static data and configuration for mentors
 */

import { Mentor } from '../types/mentor.types';

export const MENTOR_CATEGORIES = {
  FRONTEND: 'frontend',
  BACKEND: 'backend',
  AI_ML: 'ai-ml',
  FOUNDERS: 'founders',
  FULLSTACK: 'fullstack',
} as const;

export const MENTORS_DATA: Mentor[] = [
  {
    id: '1',
    slug: 'david-kim',
    name: 'David Kim',
    role: 'Lead Instructor',
    company: 'Google',
    category: 'frontend',
    avatar: '/mentors/david-kim.jpg',
    expertise: ['React', 'TypeScript', 'Frontend Architecture', 'UI/UX'],
    experience: 8,
    linkedin: 'https://linkedin.com/in/davidkim',
    bio: 'Ex-Netflix, Google. Built systems serving millions of users.',
    bio_long: 'David has 8+ years of experience building scalable frontend systems at top tech companies.',
  },
  {
    id: '2',
    slug: 'elena-rostova',
    name: 'Elena Rostova',
    role: 'AI & ML Mentor',
    company: 'OpenAI',
    category: 'ai-ml',
    avatar: '/mentors/elena-rostova.jpg',
    expertise: ['LLMs', 'Machine Learning', 'Python', 'AI Applications'],
    experience: 6,
    linkedin: 'https://linkedin.com/in/elenarостova',
    bio: 'AI researcher at OpenAI. Specializes in large language models.',
    bio_long: 'Elena is a machine learning expert focusing on LLMs and their applications.',
  },
  {
    id: '3',
    slug: 'marcus-johnson',
    name: 'Marcus Johnson',
    role: 'Full Stack Mentor',
    company: 'Stripe',
    category: 'backend',
    avatar: '/mentors/marcus-johnson.jpg',
    expertise: ['Node.js', 'System Design', 'Database Architecture', 'DevOps'],
    experience: 10,
    linkedin: 'https://linkedin.com/in/marcusjohnson',
    bio: 'Stripe engineer. Expert in building production systems.',
    bio_long: 'Marcus brings 10+ years of backend engineering expertise from leading fintech companies.',
  },
  {
    id: '4',
    slug: 'priya-sharma',
    name: 'Priya Sharma',
    role: 'Blockchain Mentor',
    company: 'Coinbase',
    category: 'founders',
    avatar: '/mentors/priya-sharma.jpg',
    expertise: ['Smart Contracts', 'Web3', 'Solidity', 'Blockchain Architecture'],
    experience: 7,
    linkedin: 'https://linkedin.com/in/priyasharma',
    bio: 'Blockchain developer at Coinbase. Building the future of Web3.',
    bio_long: 'Priya is a Web3 expert with extensive experience in smart contract development.',
  },
  {
    id: '5',
    slug: 'sarah-chen',
    name: 'Sarah Chen',
    role: 'Frontend Engineer',
    company: 'Vercel',
    category: 'frontend',
    avatar: '/mentors/sarah-chen.jpg',
    expertise: ['Next.js', 'React', 'Performance Optimization', 'Web Standards'],
    experience: 7,
    linkedin: 'https://linkedin.com/in/sarahchen',
    bio: 'Vercel engineer. Next.js expert.',
    bio_long: 'Sarah specializes in modern frontend development with Next.js and React.',
  },
  {
    id: '6',
    slug: 'james-wilson',
    name: 'James Wilson',
    role: 'Backend Architecture',
    company: 'Amazon',
    category: 'backend',
    avatar: '/mentors/james-wilson.jpg',
    expertise: ['Distributed Systems', 'Cloud Architecture', 'AWS', 'Scalability'],
    experience: 12,
    linkedin: 'https://linkedin.com/in/jameswilson',
    bio: 'AWS architect. Expert in building large-scale systems.',
    bio_long: 'James has built distributed systems at Amazon handling millions of requests per second.',
  },
  {
    id: '7',
    slug: 'anita-desai',
    name: 'Anita Desai',
    role: 'Data Scientist',
    company: 'Meta',
    category: 'ai-ml',
    avatar: '/mentors/anita-desai.jpg',
    expertise: ['Machine Learning', 'Data Engineering', 'Python', 'Analytics'],
    experience: 9,
    linkedin: 'https://linkedin.com/in/anitadesai',
    bio: 'Data scientist at Meta. ML infrastructure specialist.',
    bio_long: 'Anita builds machine learning infrastructure at one of the world\'s largest tech companies.',
  },
  {
    id: '8',
    slug: 'carlos-mendez',
    name: 'Carlos Mendez',
    role: 'Startup Founder',
    company: 'Y Combinator Alum',
    category: 'founders',
    avatar: '/mentors/carlos-mendez.jpg',
    expertise: ['Entrepreneurship', 'Product Strategy', 'Fundraising', 'Growth'],
    experience: 5,
    linkedin: 'https://linkedin.com/in/carlosmendez',
    bio: 'Y Combinator founder. Built and sold tech startup.',
    bio_long: 'Carlos is an experienced entrepreneur who has successfully founded and scaled multiple companies.',
  },
];
