/**
 * Program Feature Constants
 * All static data and configuration for programs
 */

import { Program } from '../types/program.types';

export const PROGRAM_CATEGORIES = {
  INTERNSHIP: 'internship',
  BOOTCAMP: 'bootcamp',
  APPRENTICESHIP: 'apprenticeship',
} as const;

export const PROGRAMS_DATA: Program[] = [
  {
    id: '1',
    slug: 'summer-internship',
    title: 'Summer Internship',
    description: 'Intensive 8-week program building real products from scratch. Includes mentorship and job placement support.',
    shortDescription: 'Intensive 8-week program building real products from scratch. Includes mentorship and job placement support.',
    category: 'internship',
    duration: '8 Weeks (June 10 - Aug 2)',
    commitment: 'Full-time (40 hrs/week)',
    location: 'Remote / San Francisco',
    techStack: ['C', 'HTML', 'CSS', 'JS', 'React', 'Node', 'Express', 'MongoDB', 'SQL'],
    circleColor: 'bg-[#3b6ef8]',
    outcomes: [
      {
        id: '1',
        number: 1,
        title: 'Programming Fundamentals',
        description: 'Build a strong foundation in computer science using C. Understand memory management, data structures, and algorithmic thinking before moving to higher-level languages.',
        category: 'other',
      },
      {
        id: '2',
        number: 2,
        title: 'Frontend Web Core',
        description: 'Master the building blocks of the web with HTML, CSS, and modern JavaScript (ES6+). Create responsive, accessible, and interactive user interfaces from scratch.',
        category: 'frontend',
      },
      {
        id: '3',
        number: 3,
        title: 'Advanced Frontend',
        description: 'Dive deep into React. Learn component architecture, hooks, state management, and how to build scalable single-page applications.',
        category: 'frontend',
      },
      {
        id: '4',
        number: 4,
        title: 'Backend Development',
        description: 'Construct robust server applications using Node.js and Express. Build RESTful APIs, handle authentication, and manage server logic.',
        category: 'backend',
      },
      {
        id: '5',
        number: 5,
        title: 'Database Architecture',
        description: 'Learn to design and query databases. Work with both NoSQL (MongoDB) and relational databases (SQL) to understand data modeling and persistent storage.',
        category: 'backend',
      },
      {
        id: '6',
        number: 6,
        title: 'Professional Workflows',
        description: 'Operate like a real engineering team. Master Git version control, code reviews, Agile methodologies, and deploying your full-stack applications.',
        category: 'other',
      },
    ],
  },
  {
    id: '2',
    slug: 'winter-internship',
    title: 'Winter Internship',
    description: 'A focused 4-week intensive sprint designed to transform your web development skills during the holiday break. Master modern technologies in a condensed timeline.',
    shortDescription: 'Focused 4-week sprint mastering modern web technologies. Perfect for college winter breaks.',
    category: 'internship',
    duration: '4 Weeks (Dec 16 - Jan 13)',
    commitment: 'Full-time (40 hrs/week)',
    location: 'Remote / San Francisco',
    techStack: ['React', 'Node', 'Express', 'MongoDB', 'CSS', 'Git'],
    circleColor: 'bg-[#06c5d3]',
    outcomes: [
      {
        id: '1',
        number: 1,
        title: 'React Mastery',
        description: 'Deep dive into React fundamentals, hooks, state management, and performance optimization in accelerated format.',
        category: 'frontend',
      },
      {
        id: '2',
        number: 2,
        title: 'Backend APIs',
        description: 'Build production-ready REST APIs using Node.js and Express. Handle real-world server logic and database integration.',
        category: 'backend',
      },
      {
        id: '3',
        number: 3,
        title: 'Database Design',
        description: 'Master MongoDB and SQL database design patterns. Learn to optimize queries and structure data efficiently.',
        category: 'backend',
      },
      {
        id: '4',
        number: 4,
        title: 'Full Stack Integration',
        description: 'Connect frontend and backend seamlessly. Deploy real applications and understand the complete development pipeline.',
        category: 'other',
      },
      {
        id: '5',
        number: 5,
        title: 'Version Control Workflows',
        description: 'Master Git and collaborative development. Learn professional branching strategies and code review practices.',
        category: 'other',
      },
      {
        id: '6',
        number: 6,
        title: 'Deploy to Production',
        description: 'Take your project from local development to production. Learn deployment best practices and monitoring.',
        category: 'other',
      },
    ],
  },
  {
    id: '3',
    slug: 'apprenticeship',
    title: 'Apprenticeship',
    description: 'A comprehensive 6-month paid placement with early-stage startups. Work directly with experienced engineers, contribute to real products, and build a portfolio while earning.',
    shortDescription: 'Long-term 6-month placement with our startup partners. Get paid while learning on the job.',
    category: 'apprenticeship',
    duration: '6 Months (Ongoing Cohorts)',
    commitment: 'Full-time (40 hrs/week)',
    location: 'Various (SF, NYC, Remote)',
    techStack: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'AWS', 'Full Stack'],
    circleColor: 'bg-[#0d0f1a]',
    outcomes: [
      {
        id: '1',
        number: 1,
        title: 'Real Startup Experience',
        description: 'Work on actual products with real users. Learn how startups think, move fast, and ship features under pressure.',
        category: 'other',
      },
      {
        id: '2',
        number: 2,
        title: 'Mentorship from Industry Leaders',
        description: 'Get hands-on guidance from experienced engineers who have built and shipped products at scale.',
        category: 'other',
      },
      {
        id: '3',
        number: 3,
        title: 'Full Stack Development',
        description: 'Master the complete tech stack used in production. Learn backend, frontend, DevOps, and everything in between.',
        category: 'frontend',
      },
      {
        id: '4',
        number: 4,
        title: 'Portfolio Building',
        description: 'Create impressive portfolio projects with real impact. Demonstrate your abilities to future employers with deployed applications.',
        category: 'other',
      },
      {
        id: '5',
        number: 5,
        title: 'Paid Experience',
        description: 'Earn while you learn. Get competitive compensation based on location and experience, with potential for equity.',
        category: 'other',
      },
      {
        id: '6',
        number: 6,
        title: 'Network & Opportunities',
        description: 'Build relationships with founders, investors, and fellow engineers. Open doors to future jobs and startup partnerships.',
        category: 'other',
      },
    ],
  },
  {
    id: '4',
    slug: 'ai-bootcamp',
    title: 'AI & Full Stack Bootcamp',
    description: 'A comprehensive 12-week bootcamp combining cutting-edge AI development with full-stack engineering. Build 3 production-ready AI applications using LLMs, RAG, and modern web technologies.',
    shortDescription: 'Deep dive into LLMs, RAG, and AI application development. Build 3 production-ready AI apps.',
    category: 'bootcamp',
    duration: '12 Weeks (Ongoing Cohorts)',
    commitment: 'Full-time (40 hrs/week)',
    location: 'Remote',
    techStack: ['Python', 'LLMs', 'OpenAI API', 'RAG', 'React', 'Node.js', 'FastAPI', 'Langchain'],
    circleColor: 'bg-[#3b6ef8]',
    outcomes: [
      {
        id: '1',
        number: 1,
        title: 'LLM Fundamentals',
        description: 'Master Large Language Models from the ground up. Understand how LLMs work, fine-tuning, prompt engineering, and API integration with OpenAI and other providers.',
        category: 'other',
      },
      {
        id: '2',
        number: 2,
        title: 'Retrieval Augmented Generation',
        description: 'Build sophisticated RAG systems that combine LLMs with custom data. Learn vector databases, embeddings, and semantic search for intelligent applications.',
        category: 'backend',
      },
      {
        id: '3',
        number: 3,
        title: 'AI Application Development',
        description: 'Develop production-ready AI applications. Build chatbots, recommendation engines, and intelligent automation tools using Python and modern frameworks.',
        category: 'backend',
      },
      {
        id: '4',
        number: 4,
        title: 'Full Stack Integration',
        description: 'Combine AI backends with modern frontends. Deploy AI-powered applications with React and Node.js that users can interact with.',
        category: 'frontend',
      },
      {
        id: '5',
        number: 5,
        title: 'Data Engineering Basics',
        description: 'Learn to work with data pipelines and preprocessing. Understand how to prepare and manage data for AI models at scale.',
        category: 'backend',
      },
      {
        id: '6',
        number: 6,
        title: 'Deploy & Scale AI Apps',
        description: 'Take your AI applications to production. Learn deployment, monitoring, and scaling considerations for AI-powered systems.',
        category: 'other',
      },
    ],
  },
  {
    id: '5',
    slug: 'blockchain-training',
    title: 'Blockchain Training',
    description: 'An 8-week intensive bootcamp focused on Web3 development and smart contracts. Master Solidity, build decentralized applications, and deploy production-ready blockchain projects.',
    shortDescription: 'Master smart contracts, Web3, and decentralized applications. Build your own token and exchange.',
    category: 'bootcamp',
    duration: '8 Weeks (Ongoing Cohorts)',
    commitment: 'Full-time (40 hrs/week)',
    location: 'Remote',
    techStack: ['Solidity', 'Ethereum', 'Web3.js', 'Hardhat', 'OpenZeppelin', 'React', 'Smart Contracts'],
    circleColor: 'bg-[#06c5d3]',
    outcomes: [
      {
        id: '1',
        number: 1,
        title: 'Blockchain Fundamentals',
        description: 'Understand how blockchain works from first principles. Learn about consensus mechanisms, cryptography, and the Ethereum network architecture.',
        category: 'other',
      },
      {
        id: '2',
        number: 2,
        title: 'Smart Contract Development',
        description: 'Master Solidity programming. Write secure, gas-efficient smart contracts and understand common vulnerabilities and best practices.',
        category: 'backend',
      },
      {
        id: '3',
        number: 3,
        title: 'Web3 Integration',
        description: 'Build decentralized applications (dApps) using Web3.js and ethers.js. Connect frontends to blockchain networks and interact with smart contracts.',
        category: 'frontend',
      },
      {
        id: '4',
        number: 4,
        title: 'Token Economics',
        description: 'Learn to design and deploy your own tokens. Understand ERC-20, ERC-721, and advanced token standards for various use cases.',
        category: 'other',
      },
      {
        id: '5',
        number: 5,
        title: 'DeFi Protocols',
        description: 'Study decentralized finance protocols. Build lending platforms, automated market makers, and yield farming mechanisms.',
        category: 'backend',
      },
      {
        id: '6',
        number: 6,
        title: 'Deploy & Secure',
        description: 'Deploy contracts to testnets and mainnet. Learn security auditing, testing frameworks, and best practices for production deployments.',
        category: 'other',
      },
    ],
  },
  {
    id: '6',
    slug: 'full-stack-bootcamp',
    title: 'Full Stack Bootcamp',
    description: 'A comprehensive 10-week bootcamp covering the complete modern web development stack. From frontend React to backend Node.js, databases, deployment, and DevOps.',
    shortDescription: 'Complete web development from frontend to backend. Build and deploy full-stack applications.',
    category: 'bootcamp',
    duration: '10 Weeks (Ongoing Cohorts)',
    commitment: 'Full-time (40 hrs/week)',
    location: 'Remote',
    techStack: ['React', 'Node.js', 'Express', 'PostgreSQL', 'Docker', 'AWS', 'TypeScript'],
    circleColor: 'bg-[#3b6ef8]',
    outcomes: [
      {
        id: '1',
        number: 1,
        title: 'Modern Frontend Development',
        description: 'Master React and modern JavaScript. Build responsive, performant user interfaces with state management and advanced component patterns.',
        category: 'frontend',
      },
      {
        id: '2',
        number: 2,
        title: 'Backend Architecture',
        description: 'Design and build scalable backend services using Node.js and Express. Learn API design, authentication, and middleware patterns.',
        category: 'backend',
      },
      {
        id: '3',
        number: 3,
        title: 'Database Design & Optimization',
        description: 'Master PostgreSQL and SQL. Learn relational database design, indexing, query optimization, and data modeling best practices.',
        category: 'backend',
      },
      {
        id: '4',
        number: 4,
        title: 'TypeScript & Type Safety',
        description: 'Learn TypeScript throughout the stack. Build more reliable code with strong typing in both frontend and backend applications.',
        category: 'other',
      },
      {
        id: '5',
        number: 5,
        title: 'DevOps & Deployment',
        description: 'Learn Docker, containerization, and cloud deployment. Deploy applications to AWS and learn CI/CD pipelines for production releases.',
        category: 'other',
      },
      {
        id: '6',
        number: 6,
        title: 'Real-world Projects',
        description: 'Build complete applications from concept to deployment. Work on real-world scenarios and create a portfolio of deployed projects.',
        category: 'other',
      },
    ],
  },
  {
    id: '7',
    slug: 'open-source-track',
    title: 'Open Source Track',
    description: 'Learn how to contribute to massive open source projects. Build your public GitHub portfolio.',
    shortDescription: 'Learn how to contribute to massive open source projects. Build your public GitHub portfolio.',
    category: 'apprenticeship',
    duration: '10 Weeks',
    commitment: 'Part-time (20 hrs/week)',
    location: 'Remote',
    techStack: ['Various', 'Git', 'GitHub', 'Open Source'],
    circleColor: 'bg-[#0d0f1a]',
  },
];
